use library_management_project;
select * from members ;
select * from branch;
select * from employees;
select * from books ;
select * from issued_status ;
select * from return_status ;

-- Quetions For Day 3
-- Q1. Create a new book record in the books table
insert into books(isbn,book_title,category,rental_price,status,author,publisher)
values('978-1-60129-456-2','To Kill a Mockingbird','Classic',6.00,'yes','Harper Lee','J.B. Lippincott & Co.');


-- Q2. Update the address of the member with member_id = 'C103'
Update members Set member_address='125 Oak St'
where member_id='C103';

-- Q3. Delete the record from issued_status
Delete from issued_status
where issued_id = 'IS121';

-- Q4. Retrieve all books issued by the employee with emp_id = 'E101'.
Select * 
from issued_status
where issued_emp_id='E101';

-- Q5 List members who have issued more than one book.
select issued_member_id,count(*) as Total_Books_Issues
from issued_status
group by issued_member_id
having Total_Books_Issues>1 ;

-- Q6. Create a new table that contains: book ISBN,book title,total number of times the book was issued
create table issued_book_count as 
select b.isbn,b.book_title,count(ist.issued_id) as issued_count
from issued_status ist
join books b
on ist.issued_book_isbn=b.isbn
group by b.isbn,b.book_title;

select * from issued_book_count;

-- Q7. Retrieve all books that belong to the category "Classic".
select * from  books
where category='Classic';

-- Q8. Find the total rental income generated by each book category.
select 
       b.category,
       sum(b.rental_price) as rental_income,
       count(*)
from issued_book_count ibc
join books b 
on ibc.isbn=b.isbn
group by b.category;

-- Q9. List members who registered in the last 180 days.
select * from members
where  reg_date>= current_date()-interval 180 day;

-- Q10. Display employees with their branch manager's name and branch details.
select e.*,
	   b.branch_id,
       e2.emp_name as manager
from employees e
join branch b 
on e.branch_id=b.branch_id
join employees e2
on b.manager_id=e2.emp_id;

-- Q11. Create a new table containing books with rental_price greater than 7.00.
create table filtered_books as 
(select * from books 
where rental_price>7);

select * from filtered_books;

-- Q12. Retrieve the list of books that have been issued but not yet returned.
select * 
from issued_status ist
left join return_status rs
on ist.issued_id=rs.issued_id
where rs.return_id is Null;